
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.oracle.invenes.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 25 17:26:44 CEST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */

@javax.jws.WebService(
                      serviceName = "InvenesSearchService",
                      portName = "InvenesSearchService",
                      targetNamespace = "http://ws.invenes.oracle.es/",
                      wsdlLocation = "file:/C:/OLGA/workspaces-eclipse/TFG-Invenes/invenes/src/main/ficheros_configuracion/wsdl/InvenesSearchService.wsdl",
                      endpointInterface = "es.oracle.invenes.ws.InvenesSearch")
                      
public class InvenesSearchImpl implements InvenesSearch {

    private static final Logger LOG = Logger.getLogger(InvenesSearchImpl.class.getName());

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getSearchFields(java.lang.String  arg0 ,)java.lang.Integer  arg1 )*
     */
    public es.oracle.invenes.ws.InvenesProperties getSearchFields(java.lang.String arg0,java.lang.Integer arg1) { 
        LOG.info("Executing operation getSearchFields");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            es.oracle.invenes.ws.InvenesProperties _return = new es.oracle.invenes.ws.InvenesProperties();
            java.util.List<es.oracle.invenes.ws.LabelValueBean> _returnLabelValueBean = new java.util.ArrayList<es.oracle.invenes.ws.LabelValueBean>();
            es.oracle.invenes.ws.LabelValueBean _returnLabelValueBeanVal1 = new es.oracle.invenes.ws.LabelValueBean();
            _returnLabelValueBeanVal1.setLabel("Label930854848");
            _returnLabelValueBeanVal1.setValue("Value1087617006");
            _returnLabelValueBean.add(_returnLabelValueBeanVal1);
            _return.getLabelValueBean().addAll(_returnLabelValueBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getSummary(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public es.oracle.invenes.ws.InvenesResult getSummary(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation getSummary");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode-1800822692");
            _return.setErrorDesc("ErrorDesc1101752584");
            _return.setResult("Result-556571144");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getAllTypes(java.lang.String  arg0 ,)java.lang.Integer  arg1 )*
     */
    public es.oracle.invenes.ws.InvenesProperties getAllTypes(java.lang.String arg0,java.lang.Integer arg1) { 
        LOG.info("Executing operation getAllTypes");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            es.oracle.invenes.ws.InvenesProperties _return = new es.oracle.invenes.ws.InvenesProperties();
            java.util.List<es.oracle.invenes.ws.LabelValueBean> _returnLabelValueBean = new java.util.ArrayList<es.oracle.invenes.ws.LabelValueBean>();
            es.oracle.invenes.ws.LabelValueBean _returnLabelValueBeanVal1 = new es.oracle.invenes.ws.LabelValueBean();
            _returnLabelValueBeanVal1.setLabel("Label-275796157");
            _returnLabelValueBeanVal1.setValue("Value627379748");
            _returnLabelValueBean.add(_returnLabelValueBeanVal1);
            _return.getLabelValueBean().addAll(_returnLabelValueBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getBases(java.lang.String  arg0 )*
     */
    public es.oracle.invenes.ws.InvenesProperties getBases(java.lang.String arg0) { 
        LOG.info("Executing operation getBases");
        System.out.println(arg0);
        try {
            es.oracle.invenes.ws.InvenesProperties _return = new es.oracle.invenes.ws.InvenesProperties();
            java.util.List<es.oracle.invenes.ws.LabelValueBean> _returnLabelValueBean = new java.util.ArrayList<es.oracle.invenes.ws.LabelValueBean>();
            es.oracle.invenes.ws.LabelValueBean _returnLabelValueBeanVal1 = new es.oracle.invenes.ws.LabelValueBean();
            _returnLabelValueBeanVal1.setLabel("Label-2108239000");
            _returnLabelValueBeanVal1.setValue("Value1730787609");
            _returnLabelValueBean.add(_returnLabelValueBeanVal1);
            _return.getLabelValueBean().addAll(_returnLabelValueBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getImages(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public es.oracle.invenes.ws.InvenesResult getImages(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getImages");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode-1118702762");
            _return.setErrorDesc("ErrorDesc267679194");
            _return.setResult("Result1083964782");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getClaims(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public es.oracle.invenes.ws.InvenesResult getClaims(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getClaims");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode743755143");
            _return.setErrorDesc("ErrorDesc-804461384");
            _return.setResult("Result1864425168");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#doSearch(java.lang.String  arg0 ,)java.lang.Integer  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.Integer  arg6 ,)java.lang.Integer  arg7 )*
     */
    public es.oracle.invenes.ws.SearchResult doSearch(java.lang.String arg0,java.lang.Integer arg1,java.lang.String arg2,java.lang.String arg3,java.lang.String arg4,java.lang.String arg5,java.lang.Integer arg6,java.lang.Integer arg7) throws SesionExpiradaException_Exception    { 
        LOG.info("Executing operation doSearch");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        try {
            es.oracle.invenes.ws.SearchResult _return = new es.oracle.invenes.ws.SearchResult();
            _return.setErrorCod("ErrorCod-1054890437");
            _return.setErrorDesc("ErrorDesc1410948584");
            java.util.List<es.oracle.invenes.ws.Reference> _returnReferences = new java.util.ArrayList<es.oracle.invenes.ws.Reference>();
            es.oracle.invenes.ws.Reference _returnReferencesVal1 = new es.oracle.invenes.ws.Reference();
            java.util.List<java.lang.String> _returnReferencesVal1FieldNames = new java.util.ArrayList<java.lang.String>();
            _returnReferencesVal1.getFieldNames().addAll(_returnReferencesVal1FieldNames);
            java.util.List<java.lang.String> _returnReferencesVal1FieldValues = new java.util.ArrayList<java.lang.String>();
            _returnReferencesVal1.getFieldValues().addAll(_returnReferencesVal1FieldValues);
            _returnReferencesVal1.setIdReference("IdReference570143259");
            _returnReferencesVal1.setLocation(620288622);
            _returnReferencesVal1.setPublicationNumber("PublicationNumber-1807192196");
            _returnReferencesVal1.setUrlImage("UrlImage807312411");
            _returnReferencesVal1.setUrlReference("UrlReference-464457672");
            java.util.List<java.lang.Object> _returnReferencesVal1UrlsPDF = new java.util.ArrayList<java.lang.Object>();
            _returnReferencesVal1.getUrlsPDF().addAll(_returnReferencesVal1UrlsPDF);
            _returnReferences.add(_returnReferencesVal1);
            _return.getReferences().addAll(_returnReferences);
            _return.setTotalResults(Integer.valueOf(2043545669));
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SesionExpiradaException_Exception("SesionExpiradaException...");
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getWrittenOpinion(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public es.oracle.invenes.ws.InvenesResult getWrittenOpinion(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getWrittenOpinion");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode659165678");
            _return.setErrorDesc("ErrorDesc-225303191");
            _return.setResult("Result-295941133");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getSearchReport(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public es.oracle.invenes.ws.InvenesResult getSearchReport(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getSearchReport");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode-1099020445");
            _return.setErrorDesc("ErrorDesc-250554844");
            _return.setResult("Result-1449490950");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getResultFields(java.lang.String  arg0 ,)java.lang.Integer  arg1 )*
     */
    public es.oracle.invenes.ws.InvenesProperties getResultFields(java.lang.String arg0,java.lang.Integer arg1) { 
        LOG.info("Executing operation getResultFields");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            es.oracle.invenes.ws.InvenesProperties _return = new es.oracle.invenes.ws.InvenesProperties();
            java.util.List<es.oracle.invenes.ws.LabelValueBean> _returnLabelValueBean = new java.util.ArrayList<es.oracle.invenes.ws.LabelValueBean>();
            es.oracle.invenes.ws.LabelValueBean _returnLabelValueBeanVal1 = new es.oracle.invenes.ws.LabelValueBean();
            _returnLabelValueBeanVal1.setLabel("Label1985395388");
            _returnLabelValueBeanVal1.setValue("Value-1022482200");
            _returnLabelValueBean.add(_returnLabelValueBeanVal1);
            _return.getLabelValueBean().addAll(_returnLabelValueBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getDesc(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public es.oracle.invenes.ws.InvenesResult getDesc(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getDesc");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode-1385867897");
            _return.setErrorDesc("ErrorDesc-190185590");
            _return.setResult("Result-367604425");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getPDF(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public es.oracle.invenes.ws.InvenesResult getPDF(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation getPDF");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            es.oracle.invenes.ws.InvenesResult _return = new es.oracle.invenes.ws.InvenesResult();
            _return.setErrorCode("ErrorCode-2065729575");
            _return.setErrorDesc("ErrorDesc-1751332962");
            _return.setResult("Result-1716877476");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getXMLInfo(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getXMLInfo(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getXMLInfo");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1377499106";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getPublicationTypes(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public es.oracle.invenes.ws.InvenesProperties getPublicationTypes(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getPublicationTypes");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            es.oracle.invenes.ws.InvenesProperties _return = new es.oracle.invenes.ws.InvenesProperties();
            java.util.List<es.oracle.invenes.ws.LabelValueBean> _returnLabelValueBean = new java.util.ArrayList<es.oracle.invenes.ws.LabelValueBean>();
            es.oracle.invenes.ws.LabelValueBean _returnLabelValueBeanVal1 = new es.oracle.invenes.ws.LabelValueBean();
            _returnLabelValueBeanVal1.setLabel("Label-517477837");
            _returnLabelValueBeanVal1.setValue("Value-1599447152");
            _returnLabelValueBean.add(_returnLabelValueBeanVal1);
            _return.getLabelValueBean().addAll(_returnLabelValueBean);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#getResumen(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getResumen(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getResumen");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-770232466";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.oracle.invenes.ws.InvenesSearch#doLogin(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String doLogin(java.lang.String arg0,java.lang.String arg1) throws InvenesWebException_Exception    { 
        LOG.info("Executing operation doLogin");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-658348186";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvenesWebException_Exception("InvenesWebException...");
    }

}
