
/*
 * 
 */

package es.oracle.invenes.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 25 17:26:44 CEST 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "InvenesSearchService", 
                  wsdlLocation = "file:/C:/OLGA/workspaces-eclipse/TFG-Invenes/invenes/src/main/ficheros_configuracion/wsdl/InvenesSearchService.wsdl",
                  targetNamespace = "http://ws.invenes.oracle.es/") 
public class InvenesSearchService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.invenes.oracle.es/", "InvenesSearchService");
    public final static QName InvenesSearchService = new QName("http://ws.invenes.oracle.es/", "InvenesSearchService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/OLGA/workspaces-eclipse/TFG-Invenes/invenes/src/main/ficheros_configuracion/wsdl/InvenesSearchService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/OLGA/workspaces-eclipse/TFG-Invenes/invenes/src/main/ficheros_configuracion/wsdl/InvenesSearchService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InvenesSearchService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InvenesSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvenesSearchService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InvenesSearchService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public InvenesSearchService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InvenesSearchService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InvenesSearch
     */
    @WebEndpoint(name = "InvenesSearchService")
    public InvenesSearch getInvenesSearchService() {
        return super.getPort(InvenesSearchService, InvenesSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvenesSearch
     */
    @WebEndpoint(name = "InvenesSearchService")
    public InvenesSearch getInvenesSearchService(WebServiceFeature... features) {
        return super.getPort(InvenesSearchService, InvenesSearch.class, features);
    }

}
